spring.datasource.url=jdbc:mysql://localhost:3306/FREERIDER_DB
spring.datasource.username=freerider
spring.datasource.password=free.ride
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

